### ISSUE TITLE
Encrypted graphs

### ISSUE THREAD

**Issue by lkind** [mlava/quick-capture#5]
Is it correct that this extension does not work with encrypted graphs? I am having issues getting it to run on my encrypted graph. 
Could someone confirm that it should/should not work in such a scenario? If it does not work - anyone chance on getting this updated - really would like to use Todoist as quick capture as the native Roam app does not support adding captures to encrypted graphs :-(

thanks!

**Comment by lkind** [comment]
works :-P

however it does not work with projects ID - IDs that are 10 chars - only inbox work - so seems to be a limitation in the extension that should be fixed. Only workable setup is the to use a tag for sync (if you use Todoist for actual TODOs as well )

**Comment by mlava** [comment]
thanks for reporting
I thought I posted a fix for the project id character length but will check.
cheers!

**Comment by lkind** [comment]
That would be great - because based on my testing it does not work and using tags is more cumbersome on mobile - not workable on Apple watch
Thanks!

**Comment by mlava** [comment]
Thanks @lkind 
I have been under the pump and just got back to this. 
The extension uses the inbox for the quick capture source, not any project pages. This is by design.
There is a specific Todoist Task Management extension by me that syncs projects, but that's tasks not quick capture.
Is there a reason you want to use a project for quick capture and not the inbox?
